INSERT INTO sessions (id, title, speakers, price)
VALUES (UUID(), 'Null Safety in Java with JSpecify and NullAway', 'Liam Carter', 45.00),
       (UUID(), 'The Ultimate Showdown of Database Migration Tools', 'Ethan Blake, Noah Bennett', 50.00),
       (UUID(), 'Can We Trust AI-Generated Code? Maybe We''ve Been Asking the Wrong Question.', 'Mason Hayes', 40.00),
       (UUID(), '3 Dimensional Setup', 'Lucas Reed', 35.00),
       (UUID(), 'How we develop and maintain our (12 year old) DDD app', 'Owen Brooks, Caleb Foster', 48.00),
       (UUID(), 'Spring Data 4: Data Access Revisited', 'Nathan Cole', 50.00),
       (UUID(), 'From Beans to Boot, Aspects to AI', 'Ryan Mitchell, Dylan Harper, Logan West', 49.00),
       (UUID(), 'Getting your application production-ready with Actuator', 'Connor Ellis', 42.00),
       (UUID(), 'Improving Spring Boot test efficiency', 'Hunter James', 38.00),
       (UUID(), 'Putting your software on a low-carb diet', 'Carter Morgan', 44.00),
       (UUID(), 'Modern Authentication Demystified: A Deep Dive into Spring Security’s Latest Innovations',
        'Evan Parker', 50.00),
       (UUID(), 'Effortless Spring Interface Clients with Auto-Configuration and Clients Registry',
        'Aiden Scott', 46.00),
       (UUID(), 'Say Goodbye to Microservices, Say Hello to Self-Contained Systems', 'Landon Gray', 47.00),
       (UUID(), 'Taming Testing of AI apps', 'Easton Cooper', 49.00),
       (UUID(), 'Survival guide to continuously align and upgrade your Spring dependencies',
        'Colton Bailey, Ashton Hughes', 48.00),
       (UUID(), 'From Single-Shot LLMs to Intelligent Agents: Building Scalable AI Systems with Spring AI and MCP',
        'Parker Hayes', 50.00),
       (UUID(), 'Step up the performance game with Spring Boot and Project Leyden', 'Brayden Ross', 45.00),
       (UUID(), 'El Rapido! Coding like Josh Long', 'Declan Price', 42.00),
       (UUID(), 'Making sense of Crypto Market Data in real time', 'Grayson Bennett', 49.00),
       (UUID(), 'Simplifying cloud-native app testing across environments', 'Ryder Adams, Weston Carter', 47.00),
       (UUID(), 'Bootiful GraalVM', 'Sawyer Brooks, Rowan Mitchell', 50.00),
       (UUID(), 'Crafting a self-documenting Modular Monolith with DDD principles (theory not included)',
        'Finn Hayes, Jayden Scott', 48.00),
       (UUID(), 'Mastering Challenges of Cloud-Native Architectures With Spring', 'Micah Foster', 46.00),
       (UUID(), 'Spring Cloud Function in action - how to leverage Serverless Java?',
        'Bentley Morgan, Camden Ellis', 49.00),
       (UUID(), 'API Versioning In Spring Framework 7', 'Zayden Parker', 44.00),
       (UUID(), 'Modular RAG Architectures with Java and Spring AI', 'Emerson Gray', 48.00),
       (UUID(), 'The simplest way to build resilient applications', 'Jasper Ross', 47.00),
       (UUID(), 'Streamline Cloud-Native App Development Using CDEs', 'Kaden Price', 45.00),
       (UUID(), 'Selling Maintainability', 'Maddox Bennett', 49.00),
       (UUID(), 'Next level Kotlin support in Spring Boot 4', 'Rylan Carter', 48.00),
       (UUID(), 'Life with Spring Boot inside a Monorepo', 'Tanner Brooks, Holden James', 46.00),
       (UUID(), 'You don''t need Elasticsearch! Fuzzy Search with PostgreSQL and Spring Data', 'Paxton Reed', 45.00),
       (UUID(), 'Handling 400000+ visitors at the world''s largest physics lab (CERN)', 'Keegan Harper', 50.00);