spring:
  sql:
    init:
      schema-locations: classpath*:db/schema.sql
      data-locations: classpath*:db/data.sql
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=TRUE;
  jpa:
    hibernate:
      ddl-auto: update